name: Test wf
on:
  push:
    branches: ['main', 'develop']
  workflow_dispatch:
    inputs:
      cache_flg:
        description: 'cache flag'
        default: true
        required: true
        type: boolean
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: check branch
        run: |
          echo ${{ github.head_ref }}
          echo "main branch"

      - name: check input
        run: |
          echo "cache_flg: ${{ inputs.cache_flg }}"
