name: Test wf
on:
  pull_request:
    branches: ['main']
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: |
          echo "[info] This is setup job."
          sleep 30
          exit 0

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "[info] This is build job."
          sleep 30
          exit 1

  result:
    if: always()
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Return result
        run: |
          echo "[info] This is build job."
          sleep 30
          exit 0

      - name: Check job results
        run: |
          echo '${{ toJSON(needs) }}' | jq 'to_entries | map(.key + " " + .value.result) | join(" - ")'
          exit 0
